spring:
  application:
    name: catalogue-service

  security:
    user:
      name: dokshop_catalogue_user
      password: password
      roles:
        - ADMIN
  datasource:
    url: jdbc:postgresql://localhost:5433/dokshop_database
    username: dokshop
    password: dokshop
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    sql: info